In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00267/data_banknote_authentication.txt', names = ["variance", "skewness", "curtosis", "entropy", "class"])

In [3]:
df.head()

variance  skewness  curtosis  entropy  class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [4]:
# for i in range(0, 4) :
#     mini = min(df.iloc[:, i])
#     maxi = max(df.iloc[:, i])
#     df.iloc[:, i] = (df.iloc[:, i] - mini) / (maxi - mini)
# df.head()

In [5]:
def predict(weights, test) :
    value = 0
    for i in range(len(test) - 1) :
        value += weights[i + 1] * test[i]
        
    if value >= 0:
        return 1
    else:
        return 0

def training(weights, train, l_rate, epochs) :
    for i in range(epochs) :
        for j in range(len(train)) :
            prediction = predict(weights, train.iloc[j])
            loss = train.iloc[j, -1] - prediction
            weights[1:] += l_rate * loss * train.iloc[j, :4]
            weights[0] += l_rate * loss

    
    return weights

In [ ]:
sum = 0
for j in range(10) :
    train, test = train_test_split(df, test_size = 0.5)
    weights = np.zeros(5)
    epochs = 200
    l_rate = 0.1
    weights = training(weights, train, l_rate, epochs)
    correct = 0
    print(weights)
    for i in range(len(test)) :
        result = predict(weights, test.iloc[i])
        if result == test.iloc[i, -1] : 
            correct += 1
    accuracy = correct / len(test) * 100
    sum += accuracy
    
print(sum / 10)

[778.2         -3.653599    -2.268585    -2.27181322  -1.17557146]
[634.2         -4.49288818  -2.7604395   -3.461277    -2.21089424]
[843.7        -4.1328255  -3.210932   -2.0768019  -1.5131013]
[649.6         -4.82757152  -2.818394    -3.0593683   -1.74888464]
[608.2         -3.40264814  -2.514349    -2.5167      -1.73429132]
[621.2         -4.5053819   -2.7865296   -3.55839356  -1.4098362 ]
[777.3         -4.01050412  -2.9577395   -2.97706702  -1.79606816]
[640.9        -3.6260109  -2.241679   -2.5823081  -1.0153438]
[780.4        -3.2807307  -2.648031   -2.2693058  -1.1915776]
